spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: "jdbc:h2:file:@project.basedir@/.db/simplelogger"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password: ""
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    hibernate:
      ddl-auto: update
  h2:
    console.enabled: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null
